### PR TITLE
Fix GH issue matching

### LINKED ISSUE #6: Searching for existing issue needs to be stricter
While searching for an existing issue for version `0.5.0-dev-78347be`, it picked up https://github.com/protocol/bifrost-infra/issues/586 because it contains that string in the description. 
We should strictly match issues having the exact title we're looking for.

### PR DESCRIPTION
**Pull request by gmasgras**
fix #6 wherein any issue loosely matching the ipfs version string would be used. 
This strictly matches the issue title with the version string.

### CODE REVIEW

File: gh.go [hunk 1]
```diff
@@ -49,18 +49,25 @@ func searchGHIssue(name string) (*github.Issue, error){
 	found, _, err := ghClient.Search.Issues(context.TODO(), "state:open repo:"+ghOwnerRepo+" "+name, &github.SearchOptions{
```
Comment (olizilla) [inline gh.go]: > The query contains one or more search keywords and qualifiers. Qualifiers allow you to limit your search to specific areas of GitHub. The REST API supports the same qualifiers as GitHub.com.

https://developer.github.com/v3/search/#search-issues-and-pull-requests

> in:title - e.g. warning in:title matches issues with "warning" in their title.

https://help.github.com/en/github/searching-for-information-on-github/searching-issues-and-pull-requests#search-by-the-title-body-or-comments
```suggestion
	found, _, err := ghClient.Search.Issues(context.TODO(), "in:title state:open repo:"+ghOwnerRepo+" "+name, &github.SearchOptions{
```

**Review by olizilla — APPROVED** [review]
Could limit search to just the issue title, but all good 👍

File: gh.go (hunk 1 above)
Comment (gmasgras) [reply gh.go]: :+1: This will help narrow down the issues but it wouldn't strictly match the issue title with the `go-version` string, e.g.: it would also match titles like "problems with `go-version`"
